// <auto-generated />
using E_Commerce_Website.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace E_Commerce_Website.Migrations
{
    [DbContext(typeof(myContext))]
    [Migration("20240807124413_kkkkk4")]
    partial class kkkkk4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_Website.Models.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("admin_id"));

                    b.Property<string>("admin_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("admin_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("admin_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("admin_password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("admin_id");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("E_Commerce_Website.Models.Customer", b =>
                {
                    b.Property<int>("customer_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customer_id"));

                    b.Property<string>("customer_address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("customer_phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("customer_id");

                    b.ToTable("tbl_customer");
                });
#pragma warning restore 612, 618
        }
    }
}
